// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "83ac4099-5389-4e1e-a318-ed03e47a9013";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSWITCHChange();
void onMOISTUREChange();

CloudLight sWITCH;
int mOISTURE;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(sWITCH, READWRITE, ON_CHANGE, onSWITCHChange);
  ArduinoCloud.addProperty(mOISTURE, READWRITE, 1 * SECONDS, onMOISTUREChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
